/** Interventions for digital life, privacy and reputation (docs/DOCTRINE.md:
 * cyber, privacy and reputational harm). */
import type { Intervention } from "./types";

export const DIGITAL_INTERVENTIONS = [
  {
    key: "ACCOUNT_BASICS",
    title: "Use a password manager, and turn on two-factor for email, phone carrier and bank — an app or key, not SMS",
    addresses: ["ACCOUNT_TAKEOVER", "FRAUD"],
    privacyImpact: 0,
    autonomyImpact: 1,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "HIGH",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    coveredBy: "PASSWORD_MANAGER",
    tradeoffs: "An evening of setup, and one more step when you sign in somewhere new.",
    leans: { AUTONOMY: -1, HARDENING: 1 },
  },
  {
    key: "SIM_SWAP_LOCK",
    title: "Ask your mobile carrier for a PIN or lock on moving your number to a new SIM",
    addresses: ["ACCOUNT_TAKEOVER", "CRYPTO_KEYS"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Changing phones or carriers takes an extra step.",
    leans: { AUTONOMY: -1, HARDENING: 1 },
  },
  {
    key: "HARDWARE_SECURITY_KEYS",
    title: "Two hardware security keys — one kept as a spare — for email, exchanges and your password manager",
    addresses: ["ACCOUNT_TAKEOVER", "CRYPTO_KEYS"],
    privacyImpact: 0,
    autonomyImpact: 1,
    cost: "LOW",
    kind: "PRODUCT",
    provider: "RETAILER",
    benefit: "HIGH",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Lose both and recovery is slow; keep the spare somewhere else.",
    leans: { HUMAN_TECH: 1, PROCESSING: -1, HARDENING: 1 },
  },
  {
    key: "DEVICE_HYGIENE",
    title: "Let phone and laptop update themselves, remove apps you don't use, and use a long passcode with encryption on",
    addresses: ["DEVICE_COMPROMISE", "LOCATION_TRACKING"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Restarts for updates at inconvenient moments.",
    leans: { AUTONOMY: -1, PRIVACY: -1 },
  },
  {
    key: "DEVICE_CHECK",
    title: "A cyber-security specialist checks your devices and accounts for compromise and sets them up with you",
    addresses: ["DEVICE_COMPROMISE", "ACCOUNT_TAKEOVER", "LOCATION_TRACKING"],
    privacyImpact: 1,
    autonomyImpact: 0,
    cost: "MEDIUM",
    kind: "PROFESSIONAL_SERVICE",
    provider: "CYBER_SPECIALIST",
    benefit: "HIGH",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Someone you hire sees inside your phone and laptop; choose one bound to confidentiality.",
    leans: { HUMAN_TECH: -1, HARDENING: 1 },
  },
  {
    key: "SEED_BACKUP",
    title: "Write your seed phrase on paper or metal — never a photo or cloud note — keep it in two places, and test a restore",
    addresses: ["CRYPTO_KEYS", "LOCKED_OUT"],
    privacyImpact: 0,
    autonomyImpact: 1,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "HIGH",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    coveredBy: "KEYS_BACKED_UP",
    tradeoffs: "Two physical copies to keep safe instead of none.",
    leans: { PROCESSING: -1, AUTONOMY: -1, HARDENING: 1 },
    environments: ["PERSON"],
  },
  {
    key: "CUSTODY_REVIEW",
    title: "A specialist review of how you hold keys: cold storage, multi-signature, inheritance, and what happens under duress",
    addresses: ["CRYPTO_KEYS", "COERCION"],
    privacyImpact: 1,
    autonomyImpact: 1,
    cost: "HIGH",
    kind: "PROFESSIONAL_SERVICE",
    provider: "CYBER_SPECIALIST",
    benefit: "HIGH",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "The reviewer learns how your holdings are arranged, if not the keys themselves.",
    leans: { HUMAN_TECH: -1, HARDENING: 1 },
    environments: ["PERSON"],
  },
  {
    key: "LOCATION_AUDIT",
    title: "Check which apps and people can see your location, turn off what you don't need, and check car and bags for unknown trackers",
    addresses: ["LOCATION_TRACKING", "BEING_FOUND"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Some apps get less convenient without your location.",
    leans: { PRIVACY: -1, AUTONOMY: -1, PROCESSING: -1 },
  },
  {
    key: "DATA_BROKER_REMOVAL",
    title: "A privacy specialist removes your details from people-search sites and data brokers, and keeps checking",
    addresses: ["ONLINE_EXPOSURE", "BEING_FOUND"],
    privacyImpact: 1,
    autonomyImpact: 0,
    cost: "MEDIUM",
    kind: "PROFESSIONAL_SERVICE",
    provider: "PRIVACY_SPECIALIST",
    benefit: "MEDIUM",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "You give the specialist the very details you want removed.",
    leans: { PRIVACY: -1, HUMAN_TECH: -1 },
  },
  {
    key: "CLAIM_YOUR_NAME",
    title: "Claim your name on the main platforms, verify official accounts, and say publicly which accounts are really yours",
    addresses: ["IMPERSONATION"],
    privacyImpact: 1,
    autonomyImpact: 1,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Accounts to keep up, even if you never post.",
    leans: { AUTONOMY: -1 },
  },
  {
    key: "HARASSMENT_PLAYBOOK",
    title: "Decide now what you'll do if it starts: don't reply, record it with dates, report it, and limit who can comment",
    addresses: ["REPUTATION_ATTACK", "IMPERSONATION"],
    privacyImpact: 0,
    autonomyImpact: 1,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Not answering back can feel like losing.",
    leans: { AUTONOMY: -1, HUMAN_TECH: -1 },
  },
  {
    key: "REPUTATION_RESPONDER",
    title: "A reputation and crisis-response specialist on call: takedown requests, platform escalation, what to say and when",
    addresses: ["REPUTATION_ATTACK", "IMPERSONATION"],
    privacyImpact: 1,
    autonomyImpact: 2,
    cost: "HIGH",
    kind: "PROFESSIONAL_SERVICE",
    provider: "REPUTATION_RESPONSE",
    benefit: "HIGH",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "You tell them the whole story, and agree who speaks for you.",
    leans: { HUMAN_TECH: -1, AUTONOMY: 1, HARDENING: 1 },
  },
] as const satisfies readonly Intervention[];
