/** Interventions for a place: doors, entrances, alarms, cameras. */
import type { Intervention } from "./types";

export const HOME_INTERVENTIONS = [
  {
    key: "NEIGHBOUR_ARRANGEMENT",
    title: "Agree with a neighbour to keep an eye out and empty the mailbox when you're away",
    addresses: ["BURGLARY", "UNWANTED_VISITORS"],
    privacyImpact: 1,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    coveredBy: "NEIGHBOUR_CONTACT",
    tradeoffs: "Relies on someone else's attention; they learn when you are away.",
    leans: { SCOPE: 1, HUMAN_TECH: -1, AUTONOMY: -1 },
    environments: ["HOME", "WORKPLACE", "VENUE"],
  },
  {
    key: "DOOR_POLICY",
    title: "Don't open to unannounced visitors; speak through the closed door or intercom",
    addresses: ["UNWANTED_VISITORS"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Can feel awkward with deliveries or officials; ask for ID through the door.",
    leans: { PRIVACY: -1, AUTONOMY: -1, HUMAN_TECH: -1 },
    environments: ["HOME", "WORKPLACE", "VENUE"],
  },
  {
    key: "LIVED_IN_ROUTINE",
    title: "Make the home look lived-in: a lamp on a timer you already own, blinds as usual",
    addresses: ["BURGLARY"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "ENVIRONMENTAL",
    benefit: "LOW",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Deters opportunists, not a determined intruder.",
    leans: { PRIVACY: -1, AUTONOMY: -1, HARDENING: -1 },
    environments: ["HOME", "WORKPLACE", "VENUE"],
  },
  {
    key: "DOOR_VIEWER_FIT",
    title: "Fit a door viewer or chain",
    addresses: ["UNWANTED_VISITORS"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "LOW",
    kind: "PRODUCT",
    provider: "INSTALLER",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    coveredBy: "DOOR_VIEWER",
    tradeoffs: "Renters need the landlord's consent to drill.",
    leans: { PRIVACY: -1, AUTONOMY: -1, HARDENING: 1 },
    environments: ["HOME", "WORKPLACE", "VENUE"],
  },
  {
    key: "ENTRANCE_LIGHT",
    title: "Motion light at the entrance (no camera)",
    addresses: ["ARRIVING_AT_NIGHT", "BURGLARY"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "LOW",
    kind: "PRODUCT",
    provider: "INSTALLER",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    coveredBy: "ENTRANCE_LIGHTING",
    tradeoffs: "May need building management's approval; can bother neighbours.",
    leans: { PRIVACY: -1, AUTONOMY: 1, HUMAN_TECH: 1, SCOPE: 1 },
    environments: ["HOME", "WORKPLACE", "VENUE"],
  },
  {
    key: "LOCK_UPGRADE",
    title: "Upgrade to a security cylinder and strike plate",
    addresses: ["BURGLARY"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "MEDIUM",
    kind: "PRODUCT",
    provider: "INSTALLER",
    benefit: "HIGH",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    coveredBy: "SOLID_DOOR_LOCK",
    tradeoffs: "Real cost; renters need the landlord's consent.",
    leans: { PRIVACY: -1, HUMAN_TECH: 1, HARDENING: 1 },
    environments: ["HOME", "WORKPLACE", "VENUE"],
  },
  {
    key: "LOCAL_SIREN_ALARM",
    title: "Local siren alarm on the door, no monitoring centre",
    addresses: ["BURGLARY"],
    privacyImpact: 1,
    autonomyImpact: 1,
    cost: "MEDIUM",
    kind: "PRODUCT",
    provider: "RETAILER",
    benefit: "MEDIUM",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Nobody is called; false alarms annoy neighbours.",
    leans: { AUTONOMY: 1, HUMAN_TECH: 1, PROCESSING: -1, DISCRETION: 1, HARDENING: 1 },
    environments: ["HOME", "WORKPLACE", "VENUE"],
  },
  {
    key: "LOCAL_DOORBELL_CAMERA",
    title: "Doorbell camera recording to a card at home, pointed only at your door",
    addresses: ["UNWANTED_VISITORS", "BURGLARY"],
    privacyImpact: 2,
    autonomyImpact: 1,
    cost: "MEDIUM",
    kind: "PRODUCT",
    provider: "INSTALLER",
    benefit: "MEDIUM",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: ["NO_PERSISTENT_RECORDING", "NO_EXTERIOR_CAMERAS"],
    tradeoffs: "Records neighbours and passers-by; Swiss data-protection rules apply to shared areas.",
    leans: { PRIVACY: 1, AUTONOMY: 1, HUMAN_TECH: 1, PROCESSING: -1, DISCRETION: 1 },
    environments: ["HOME", "WORKPLACE", "VENUE"],
  },
  {
    key: "CLOUD_DOORBELL_CAMERA",
    title: "Cloud doorbell camera with face recognition",
    addresses: ["UNWANTED_VISITORS", "BURGLARY"],
    privacyImpact: 3,
    autonomyImpact: 2,
    cost: "HIGH",
    kind: "PRODUCT",
    provider: "RETAILER",
    benefit: "MEDIUM",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: [
      "NO_CLOUD_VIDEO",
      "NO_FACIAL_RECOGNITION",
      "LOCAL_ONLY_PROCESSING",
      "NO_PERSISTENT_RECORDING",
      "NO_EXTERIOR_CAMERAS",
    ],
    tradeoffs: "Video and faces sit with a vendor who can share them without you deciding.",
    leans: { PRIVACY: 1, AUTONOMY: 1, HUMAN_TECH: 1, PROCESSING: 1, DISCRETION: 1 },
    environments: ["HOME", "WORKPLACE", "VENUE"],
  },
  {
    key: "INDOOR_CAMERA",
    title: "Indoor camera",
    addresses: ["BURGLARY"],
    privacyImpact: 3,
    autonomyImpact: 2,
    cost: "MEDIUM",
    kind: "PRODUCT",
    provider: "RETAILER",
    benefit: "LOW",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: ["NO_INTERIOR_CAMERAS", "NO_CLOUD_VIDEO", "NO_PERSISTENT_RECORDING"],
    tradeoffs: "Films your private life and anyone who visits.",
    leans: { PRIVACY: 1, AUTONOMY: 1, HUMAN_TECH: 1, PROCESSING: 1 },
    environments: ["HOME", "WORKPLACE"],
  },
  {
    key: "MONITORED_ALARM",
    title: "Monitored alarm with automatic police dispatch",
    addresses: ["BURGLARY"],
    privacyImpact: 2,
    autonomyImpact: 2,
    cost: "HIGH",
    kind: "PROFESSIONAL_SERVICE",
    provider: "ALARM_MONITORING",
    benefit: "HIGH",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: ["NO_AUTO_POLICE_SHARING", "LOCAL_ONLY_PROCESSING"],
    tradeoffs: "Subscription; alarms go to the police without you deciding.",
    leans: { AUTONOMY: 1, HUMAN_TECH: 1, PROCESSING: 1, DISCRETION: 1, HARDENING: 1 },
    environments: ["HOME", "WORKPLACE", "VENUE"],
  },
] as const satisfies readonly Intervention[];
