/** Interventions for family, health and money (docs/DOCTRINE.md: family,
 * health/emergency and financial harm). First aid complements medical care;
 * it never replaces it. */
import type { Intervention } from "./types";

export const HOUSEHOLD_INTERVENTIONS = [
  {
    key: "FAMILY_RULES",
    title: "Agree simple rules with your children — who they may go with, what never to share online — and that they can always call you, no questions asked",
    addresses: ["CHILDREN_SAFETY"],
    privacyImpact: 0,
    autonomyImpact: 1,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "A conversation to repeat as they grow; trust instead of tracking.",
    leans: { PRIVACY: -1, HUMAN_TECH: -1, AUTONOMY: -1 },
  },
  {
    key: "FAMILY_WORKSHOP",
    title: "A family safety workshop: parents and children practise what to do if lost, approached or bullied online",
    addresses: ["CHILDREN_SAFETY"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "MEDIUM",
    kind: "PROFESSIONAL_SERVICE",
    provider: "PREPAREDNESS_TRAINER",
    benefit: "MEDIUM",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "An afternoon together; children remember what they practised.",
    leans: { HUMAN_TECH: -1, SCOPE: 1 },
    environments: ["PERSON", "HOME"],
  },
  {
    key: "FAMILY_CODE_WORD",
    title: "Agree a family code word, and call back on a number you already have before sending money to anyone who says they're family",
    addresses: ["RELATIVE_TARGETED", "FRAUD"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "HIGH",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    coveredBy: "CODE_WORD",
    tradeoffs: "Slightly awkward the first time a real relative is asked for it.",
    leans: { HUMAN_TECH: -1, AUTONOMY: -1 },
    environments: ["PERSON"],
  },
  {
    key: "EMERGENCY_BASICS",
    title: "Know 144 (ambulance), 117 (police), 118 (fire) and 112; set an emergency contact on your phone; know where the nearest defibrillator is",
    addresses: ["MEDICAL_EMERGENCY"],
    privacyImpact: 1,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Your emergency contact is readable from the lock screen.",
    leans: { AUTONOMY: -1 },
  },
  {
    key: "FIRST_AID_COURSE",
    title: "A first-aid course for you, your household or your staff",
    addresses: ["MEDICAL_EMERGENCY"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "MEDIUM",
    kind: "PROFESSIONAL_SERVICE",
    provider: "PREPAREDNESS_TRAINER",
    benefit: "HIGH",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    coveredBy: "FIRST_AIDER",
    tradeoffs: "A day or two of your time; worth refreshing every few years.",
    leans: { HUMAN_TECH: -1, AUTONOMY: -1 },
  },
  {
    key: "PAUSE_BEFORE_PAYING",
    title: "Never act on an urgent call or message asking for money, codes or keys: hang up and call back on a number you already have",
    addresses: ["FRAUD", "RELATIVE_TARGETED"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "HIGH",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "A real emergency waits a few minutes longer.",
    leans: { AUTONOMY: -1 },
  },
  {
    key: "SMALL_AMOUNTS_REACHABLE",
    title: "Keep only small amounts reachable day to day; put delays or a second signer on the rest",
    addresses: ["COERCION", "FRAUD", "CRYPTO_KEYS"],
    privacyImpact: 0,
    autonomyImpact: 1,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "HIGH",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Moving larger sums takes planning, or another person.",
    leans: { AUTONOMY: -1, HARDENING: 1 },
  },
] as const satisfies readonly Intervention[];
