/** Interventions for a person: routines, journeys, online exposure, occasions. */
import type { Intervention } from "./types";

export const PERSONAL_INTERVENTIONS = [
  {
    key: "CHECK_IN_ROUTINE",
    title: "Message one trusted person when you leave and when you're home",
    addresses: ["ARRIVING_AT_NIGHT", "BEING_FOUND", "FOLLOWED"],
    privacyImpact: 1,
    autonomyImpact: 1,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    coveredBy: "CHECK_IN_CONTACT",
    tradeoffs: "Someone you trust knows your timing; agree what they do if you go quiet.",
    leans: { HUMAN_TECH: -1, AUTONOMY: -1, SCOPE: 1 },
  },
  {
    key: "ADDRESS_BLOCK",
    title:
      "Remove your address from public directories and ask the Personenmeldeamt for a data-release block",
    addresses: ["BEING_FOUND", "ONLINE_EXPOSURE"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "HIGH",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    coveredBy: "ADDRESS_BLOCKED",
    tradeoffs: "Some paperwork; legitimate senders may find you harder to reach.",
    leans: { PRIVACY: -1, AUTONOMY: -1 },
    environments: ["HOME"],
  },
  {
    key: "ACCOMPANIED_HOME",
    title: "Book a Skif Protector to accompany you home on the nights that worry you",
    addresses: ["ARRIVING_AT_NIGHT", "BEING_FOUND", "FOLLOWED"],
    privacyImpact: 1,
    autonomyImpact: 1,
    cost: "MEDIUM",
    kind: "PROTECTOR",
    benefit: "HIGH",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: ["NO_HUMAN_PROTECTOR"],
    tradeoffs: "A paid service each time; a Protector learns your address.",
    leans: { HUMAN_TECH: -1, HARDENING: 1 },
  },
  {
    key: "DIGITAL_FOOTPRINT_CLEANUP",
    title: "Take personal details off public profiles and people-search sites; keep public and private accounts apart",
    addresses: ["ONLINE_EXPOSURE", "BEING_FOUND"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "An afternoon of work, and repeating it now and then.",
    leans: { PRIVACY: -1, AUTONOMY: -1 },
  },
  {
    key: "HOLDINGS_DISCRETION",
    title: "Keep holdings out of view: don't tie wallets or amounts to your name, in public or online",
    addresses: ["ONLINE_EXPOSURE"],
    privacyImpact: 0,
    autonomyImpact: 1,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Asks you to talk less about something you may be proud of.",
    leans: { PRIVACY: -1, AUTONOMY: -1 },
  },
  {
    key: "PRIVACY_REVIEW",
    title: "A professional review of your physical and digital exposure",
    addresses: ["ONLINE_EXPOSURE", "BEING_FOUND"],
    privacyImpact: 1,
    autonomyImpact: 0,
    cost: "MEDIUM",
    kind: "PROFESSIONAL_SERVICE",
    benefit: "HIGH",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "You share details with the reviewer so they can find what others could.",
    leans: { HUMAN_TECH: -1, HARDENING: 1 },
  },
  {
    key: "ROUTE_VARIATION",
    title: "Vary your route and timing; keep to lit, busy streets",
    addresses: ["FOLLOWED", "ARRIVING_AT_NIGHT"],
    privacyImpact: 0,
    autonomyImpact: 1,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Sometimes a longer way home.",
    leans: { PRIVACY: -1, AUTONOMY: -1 },
  },
  {
    key: "PERSONAL_ALARM",
    title: "A personal alarm — loud, no app, no tracking",
    addresses: ["FOLLOWED", "ARRIVING_AT_NIGHT"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "LOW",
    kind: "PRODUCT",
    benefit: "LOW",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Draws attention; helps only if people are near.",
    leans: { HUMAN_TECH: 1, PROCESSING: -1, DISCRETION: 1 },
  },
  {
    key: "LIVE_LOCATION_SHARING",
    title: "Share your live location with one trusted person on the way",
    addresses: ["FOLLOWED", "ARRIVING_AT_NIGHT"],
    privacyImpact: 2,
    autonomyImpact: 1,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: ["LOCAL_ONLY_PROCESSING"],
    tradeoffs: "Your location passes through an app provider's servers while shared.",
    leans: { PRIVACY: 1, HUMAN_TECH: 1, PROCESSING: 1 },
  },
  {
    key: "PLAN_SHARED",
    title: "Share the plan — where, when, with whom — with one trusted person, and agree a check-in time",
    addresses: ["UPCOMING_EVENT"],
    privacyImpact: 1,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Someone you trust knows your plans for the day.",
    leans: { HUMAN_TECH: -1, AUTONOMY: -1 },
  },
  {
    key: "EVENT_PROTECTOR",
    title: "Book a Protector for that occasion",
    addresses: ["UPCOMING_EVENT"],
    privacyImpact: 1,
    autonomyImpact: 1,
    cost: "MEDIUM",
    kind: "PROTECTOR",
    benefit: "HIGH",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: ["NO_HUMAN_PROTECTOR"],
    tradeoffs: "A paid service; a Protector learns where you'll be.",
    leans: { HUMAN_TECH: -1, HARDENING: 1 },
  },
] as const satisfies readonly Intervention[];
