/** Interventions for surroundings, institutions and what happens when
 * prevention fails (docs/DOCTRINE.md: environmental, institutional and
 * resilience harm). Skif points to professionals for rights and law; it never
 * pretends to be one. */
import type { Intervention } from "./types";

export const RESILIENCE_INTERVENTIONS = [
  {
    key: "HAZARD_WALKTHROUGH",
    title: "Test the smoke alarms, find the gas and water shut-offs, and keep two ways out clear",
    addresses: ["HAZARD"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "ENVIRONMENTAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Half an hour, once or twice a year.",
    leans: { AUTONOMY: -1 },
  },
  {
    key: "SMOKE_ALARMS_FIT",
    title: "Standalone smoke alarms (no app) and a fire blanket",
    addresses: ["HAZARD"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "LOW",
    kind: "PRODUCT",
    provider: "RETAILER",
    benefit: "HIGH",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    coveredBy: "SMOKE_ALARMS",
    tradeoffs: "The occasional false alarm while cooking.",
    leans: { PROCESSING: -1, HUMAN_TECH: 1 },
    environments: ["HOME", "WORKPLACE", "VENUE"],
  },
  {
    key: "KNOW_THE_AREA",
    title: "Know the nearest police post, hospital, pharmacy and a late-open place you could step into; save them offline",
    addresses: ["UNFAMILIAR_AREA"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "A little homework before a trip or a move.",
    leans: { AUTONOMY: -1, PROCESSING: -1 },
  },
  {
    key: "MEET_THE_NEIGHBOURS",
    title: "Introduce yourself to two neighbours, and join the building or neighbourhood group",
    addresses: ["UNFAMILIAR_AREA", "NO_PLAN"],
    privacyImpact: 1,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "People nearby know a little more about you.",
    leans: { SCOPE: 1, HUMAN_TECH: -1 },
    environments: ["PERSON", "HOME"],
  },
  {
    key: "DATA_ACCESS_REQUEST",
    title: "Ask any Swiss company or authority what it holds about you — free under the Data Protection Act — and have wrong or unneeded data corrected or deleted",
    addresses: ["INSTITUTION_DATA"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Letters to write, and up to 30 days for each answer.",
    leans: { PRIVACY: -1, AUTONOMY: -1 },
  },
  {
    key: "RIGHTS_GUIDE",
    title: "Read a plain-language guide to your rights with police, authorities and employers from a legal-aid service, and write down what happened right after any encounter",
    addresses: ["KNOWING_MY_RIGHTS"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "A guide is not advice about your case.",
    leans: { AUTONOMY: -1 },
  },
  {
    key: "LAWYER_REFERRAL",
    title: "A first consultation with an independent lawyer — Skif refers you, it never gives legal advice itself",
    addresses: ["KNOWING_MY_RIGHTS", "INSTITUTION_DATA", "IMPERSONATION", "COERCION"],
    privacyImpact: 1,
    autonomyImpact: 0,
    cost: "MEDIUM",
    kind: "PROFESSIONAL_SERVICE",
    provider: "LEGAL",
    benefit: "HIGH",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Paid by the hour; what you tell a lawyer stays privileged.",
    leans: { HUMAN_TECH: -1 },
    environments: ["PERSON", "WORKPLACE", "VENUE"],
  },
  {
    key: "RECOVERY_KIT",
    title: "Print account recovery codes, note where keys and documents are, and keep it sealed in a safe or with one trusted person",
    addresses: ["LOCKED_OUT", "NO_PLAN"],
    privacyImpact: 1,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "HIGH",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    coveredBy: "RECOVERY_STORED",
    tradeoffs: "Whoever holds the envelope must be someone you'd trust with everything in it.",
    leans: { PROCESSING: -1, HUMAN_TECH: -1, AUTONOMY: -1 },
  },
  {
    key: "EMERGENCY_PLAN",
    title: "Write a one-page emergency plan: who calls whom, where to meet, a contact outside the city, and what to grab",
    addresses: ["NO_PLAN", "CHILDREN_SAFETY", "MEDICAL_EMERGENCY", "HAZARD"],
    privacyImpact: 1,
    autonomyImpact: 0,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    coveredBy: "FAMILY_PLAN",
    tradeoffs: "An hour together; the people on it know each other's numbers.",
    leans: { HUMAN_TECH: -1, SCOPE: 1 },
  },
  {
    key: "PREPAREDNESS_SESSION",
    title: "A preparedness session with a trainer: your plan practised once, with first aid and getting out safely",
    addresses: ["NO_PLAN", "MEDICAL_EMERGENCY", "HAZARD"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "MEDIUM",
    kind: "PROFESSIONAL_SERVICE",
    provider: "PREPAREDNESS_TRAINER",
    benefit: "MEDIUM",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "A few hours; practising once makes a plan real.",
    leans: { HUMAN_TECH: -1, SCOPE: 1 },
  },
  {
    key: "INCIDENT_RESPONDER",
    title: "A cyber incident-response contact on retainer, for when an account, device or key is compromised",
    addresses: ["LOCKED_OUT", "ACCOUNT_TAKEOVER", "DEVICE_COMPROMISE"],
    privacyImpact: 1,
    autonomyImpact: 0,
    cost: "HIGH",
    kind: "PROFESSIONAL_SERVICE",
    provider: "CYBER_SPECIALIST",
    benefit: "MEDIUM",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "A standing fee for something you hope never to use.",
    leans: { HUMAN_TECH: -1, HARDENING: 1 },
  },
] as const satisfies readonly Intervention[];
