/** Interventions for venues and events: guests, staff, crowds. */
import type { Intervention } from "./types";

export const VENUE_INTERVENTIONS = [
  {
    key: "HOUSE_RULES_BRIEFING",
    title: "Clear house rules at the door, and a short de-escalation briefing for staff before each night",
    addresses: ["GUEST_CONFLICT"],
    privacyImpact: 0,
    autonomyImpact: 1,
    cost: "FREE",
    kind: "BEHAVIOURAL",
    benefit: "MEDIUM",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    tradeoffs: "Someone has to own it every night.",
    leans: { HUMAN_TECH: -1, SCOPE: 1 },
    environments: ["VENUE", "EVENT", "WORKPLACE"],
  },
  {
    key: "DEESCALATION_TRAINING",
    title: "De-escalation training for your staff",
    addresses: ["GUEST_CONFLICT", "UNWANTED_VISITORS"],
    privacyImpact: 0,
    autonomyImpact: 0,
    cost: "MEDIUM",
    kind: "PROFESSIONAL_SERVICE",
    benefit: "HIGH",
    evidence: { confidence: "MEDIUM", basis: "SKIF_JUDGMENT" },
    conflictsWith: [],
    coveredBy: "STAFF_TRAINED",
    tradeoffs: "Staff time off the floor; worth repeating as people change.",
    leans: { HUMAN_TECH: -1, SCOPE: 1 },
    environments: ["VENUE", "EVENT", "WORKPLACE"],
  },
  {
    key: "VENUE_PROTECTORS",
    title: "Book Skif de-escalation staff for your busiest nights",
    addresses: ["GUEST_CONFLICT"],
    privacyImpact: 1,
    autonomyImpact: 0,
    cost: "HIGH",
    kind: "PROTECTOR",
    benefit: "HIGH",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: ["NO_HUMAN_PROTECTOR"],
    tradeoffs: "A paid service each night; guests notice more staff.",
    leans: { HUMAN_TECH: -1, DISCRETION: 1, HARDENING: 1 },
    environments: ["VENUE", "EVENT", "WORKPLACE"],
  },
  {
    key: "VENUE_CCTV",
    title: "CCTV over the public areas of the venue, recorded on site",
    addresses: ["GUEST_CONFLICT", "BURGLARY"],
    privacyImpact: 3,
    autonomyImpact: 1,
    cost: "HIGH",
    kind: "PRODUCT",
    benefit: "LOW",
    evidence: { confidence: "LOW", basis: "SKIF_JUDGMENT" },
    conflictsWith: ["NO_PERSISTENT_RECORDING"],
    tradeoffs: "Films every guest; helps after the fact more than in the moment. Data-protection duties apply.",
    leans: { PRIVACY: 1, HUMAN_TECH: 1, DISCRETION: 1, HARDENING: 1 },
    environments: ["VENUE", "EVENT", "WORKPLACE"],
  },
] as const satisfies readonly Intervention[];
